---
version: '2'
services:
  robo-jenkins:
    build: robo-jenkins/.
    ports:
      - "80:8080"
    environment:
      DOCKER_HOST: 'tcp://localhost:2375'
    #   # to override defaults
    #   - "GIT_COMMITTER_NAME="
    #   - "GIT_COMMITTER_EMAIL="
    #   - "JENKINS_EXECUTERS="
    #   - "JENKINS_URL="
    #   - "ROBO_DEFAULT_JOB="
    volumes:
      - "./testing/data/repos/:/usr/share/jenkins/repo_registry/"

  registry:
    image: registry:2
    # For dind, share network stack with Jenkins
    network_mode: "service:robo-jenkins"

  dind:
    image: docker:1.12.3-dind
    privileged: true
    volumes:
    - /lib/modules:/lib/modules
    network_mode: "service:robo-jenkins"
    # Uncomment to use overlay storage driver instead of vfs
    # Much faster, but requires setting the storgage driver of the docker daemon
    # That runs the dind container to overlay, which is non trivial on docker for mac
    # But can be done as in: http://stackoverflow.com/questions/39455764/change-storage-driver-for-docker-on-os-x
    #command: --storage-driver=overlay
