---
version: '2'
services:

  robo-jenkins:
    build: robo-jenkins/.
    ports:
      - "80:8080"
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      REGISTRY_USER:
      REGISTRY_PW:
      REGISTRY_HOST: quay.io
      GIT_HTTPS_USER:
      GIT_HTTPS_PW:
      GIT_HOST: github.com
      #GIT_COMMITTER_NAME:
      #GIT_COMMITTER_EMAIL:
      #JENKINS_EXECUTERS:
      #JENKINS_URL:
      #ROBO_JENKINS_DEFAULT_JOB:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./testing/data/repos/:/usr/share/jenkins/repo_registry/"

  registry:
    image: registry:2
    # For host docker, use the port network, binding to localhost specifically
    ports:
    - "localhost:5000:5000"
