---
version: '2'
services:

  robo-jenkins:
    build: robo-jenkins/.
    ports:
      - "80:8080"
    env_file: testing/data/developer.env
    #environment:
      #GIT_COMMITTER_NAME:
      #GIT_COMMITTER_EMAIL:
      #JENKINS_EXECUTERS:
      #JENKINS_URL:
      #ROBO_DEFAULT_JOB:
      #ROBO_JOB_TEMPLATE_REPO:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./testing/data/repos/:/usr/share/jenkins/userContent/repo_registry/"

  registry:
    image: registry:2
    # For host docker, use the port network, binding to localhost specifically
    ports:
    - "localhost:5000:5000"
