---
version: '2'
services:

  robo-jenkins:
    build: robo-jenkins/.
    ports:
      - "80:8080"
    # environment:
    #   # to override defaults
    #   - "GIT_COMMITTER_NAME="
    #   - "GIT_COMMITTER_EMAIL="
    #   - "JENKINS_EXECUTERS="
    #   - "JENKINS_URL="
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/testing/data/repos/:/usr/share/jenkins/repo_registry/"
